// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RhbOutputDataMessage.proto

package kh.dev.scott.movie.core.proto.data;

/**
 * Protobuf type {@code kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage}
 */
public  final class RhbOutputDataMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage)
    RhbOutputDataMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RhbOutputDataMessage.newBuilder() to construct.
  private RhbOutputDataMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RhbOutputDataMessage() {
    id_ = 0L;
    title_ = "";
    category_ = "";
    star_ = "";
    items_ = java.util.Collections.emptyList();
    createAt_ = "";
    updateAt_ = "";
    timestamp_ = "";
    traceNo_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RhbOutputDataMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            category_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            star_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              items_ = new java.util.ArrayList<kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage>();
              mutable_bitField0_ |= 0x00000010;
            }
            items_.add(
                input.readMessage(kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.parser(), extensionRegistry));
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            createAt_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            updateAt_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            timestamp_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            traceNo_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kh.dev.scott.movie.core.proto.data.RhbOutputDataMessageOuterClass.internal_static_kh_dev_scott_movie_core_proto_data_RhbOutputDataMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kh.dev.scott.movie.core.proto.data.RhbOutputDataMessageOuterClass.internal_static_kh_dev_scott_movie_core_proto_data_RhbOutputDataMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage.class, kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 2;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_FIELD_NUMBER = 3;
  private volatile java.lang.Object category_;
  /**
   * <code>string category = 3;</code>
   */
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <code>string category = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAR_FIELD_NUMBER = 4;
  private volatile java.lang.Object star_;
  /**
   * <code>string star = 4;</code>
   */
  public java.lang.String getStar() {
    java.lang.Object ref = star_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      star_ = s;
      return s;
    }
  }
  /**
   * <code>string star = 4;</code>
   */
  public com.google.protobuf.ByteString
      getStarBytes() {
    java.lang.Object ref = star_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      star_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEMS_FIELD_NUMBER = 5;
  private java.util.List<kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage> items_;
  /**
   * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
   */
  public java.util.List<kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
   */
  public java.util.List<? extends kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessageOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
   */
  public kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
   */
  public kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessageOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int CREATE_AT_FIELD_NUMBER = 6;
  private volatile java.lang.Object createAt_;
  /**
   * <code>string create_at = 6;</code>
   */
  public java.lang.String getCreateAt() {
    java.lang.Object ref = createAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createAt_ = s;
      return s;
    }
  }
  /**
   * <code>string create_at = 6;</code>
   */
  public com.google.protobuf.ByteString
      getCreateAtBytes() {
    java.lang.Object ref = createAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATE_AT_FIELD_NUMBER = 7;
  private volatile java.lang.Object updateAt_;
  /**
   * <code>string update_at = 7;</code>
   */
  public java.lang.String getUpdateAt() {
    java.lang.Object ref = updateAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updateAt_ = s;
      return s;
    }
  }
  /**
   * <code>string update_at = 7;</code>
   */
  public com.google.protobuf.ByteString
      getUpdateAtBytes() {
    java.lang.Object ref = updateAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updateAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 8;
  private volatile java.lang.Object timestamp_;
  /**
   * <code>string timestamp = 8;</code>
   */
  public java.lang.String getTimestamp() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestamp_ = s;
      return s;
    }
  }
  /**
   * <code>string timestamp = 8;</code>
   */
  public com.google.protobuf.ByteString
      getTimestampBytes() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACENO_FIELD_NUMBER = 9;
  private volatile java.lang.Object traceNo_;
  /**
   * <code>string traceNo = 9;</code>
   */
  public java.lang.String getTraceNo() {
    java.lang.Object ref = traceNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceNo_ = s;
      return s;
    }
  }
  /**
   * <code>string traceNo = 9;</code>
   */
  public com.google.protobuf.ByteString
      getTraceNoBytes() {
    java.lang.Object ref = traceNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!getCategoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, category_);
    }
    if (!getStarBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, star_);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(5, items_.get(i));
    }
    if (!getCreateAtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, createAt_);
    }
    if (!getUpdateAtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, updateAt_);
    }
    if (!getTimestampBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, timestamp_);
    }
    if (!getTraceNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, traceNo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!getCategoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, category_);
    }
    if (!getStarBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, star_);
    }
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, items_.get(i));
    }
    if (!getCreateAtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, createAt_);
    }
    if (!getUpdateAtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, updateAt_);
    }
    if (!getTimestampBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, timestamp_);
    }
    if (!getTraceNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, traceNo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage)) {
      return super.equals(obj);
    }
    kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage other = (kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getCategory()
        .equals(other.getCategory());
    result = result && getStar()
        .equals(other.getStar());
    result = result && getItemsList()
        .equals(other.getItemsList());
    result = result && getCreateAt()
        .equals(other.getCreateAt());
    result = result && getUpdateAt()
        .equals(other.getUpdateAt());
    result = result && getTimestamp()
        .equals(other.getTimestamp());
    result = result && getTraceNo()
        .equals(other.getTraceNo());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    hash = (37 * hash) + STAR_FIELD_NUMBER;
    hash = (53 * hash) + getStar().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (37 * hash) + CREATE_AT_FIELD_NUMBER;
    hash = (53 * hash) + getCreateAt().hashCode();
    hash = (37 * hash) + UPDATE_AT_FIELD_NUMBER;
    hash = (53 * hash) + getUpdateAt().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp().hashCode();
    hash = (37 * hash) + TRACENO_FIELD_NUMBER;
    hash = (53 * hash) + getTraceNo().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage)
      kh.dev.scott.movie.core.proto.data.RhbOutputDataMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kh.dev.scott.movie.core.proto.data.RhbOutputDataMessageOuterClass.internal_static_kh_dev_scott_movie_core_proto_data_RhbOutputDataMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kh.dev.scott.movie.core.proto.data.RhbOutputDataMessageOuterClass.internal_static_kh_dev_scott_movie_core_proto_data_RhbOutputDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage.class, kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage.Builder.class);
    }

    // Construct using kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      title_ = "";

      category_ = "";

      star_ = "";

      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        itemsBuilder_.clear();
      }
      createAt_ = "";

      updateAt_ = "";

      timestamp_ = "";

      traceNo_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kh.dev.scott.movie.core.proto.data.RhbOutputDataMessageOuterClass.internal_static_kh_dev_scott_movie_core_proto_data_RhbOutputDataMessage_descriptor;
    }

    @java.lang.Override
    public kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage getDefaultInstanceForType() {
      return kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage.getDefaultInstance();
    }

    @java.lang.Override
    public kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage build() {
      kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage buildPartial() {
      kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage result = new kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.title_ = title_;
      result.category_ = category_;
      result.star_ = star_;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      result.createAt_ = createAt_;
      result.updateAt_ = updateAt_;
      result.timestamp_ = timestamp_;
      result.traceNo_ = traceNo_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage) {
        return mergeFrom((kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage other) {
      if (other == kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        onChanged();
      }
      if (!other.getStar().isEmpty()) {
        star_ = other.star_;
        onChanged();
      }
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000010);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (!other.getCreateAt().isEmpty()) {
        createAt_ = other.createAt_;
        onChanged();
      }
      if (!other.getUpdateAt().isEmpty()) {
        updateAt_ = other.updateAt_;
        onChanged();
      }
      if (!other.getTimestamp().isEmpty()) {
        timestamp_ = other.timestamp_;
        onChanged();
      }
      if (!other.getTraceNo().isEmpty()) {
        traceNo_ = other.traceNo_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object category_ = "";
    /**
     * <code>string category = 3;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string category = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string category = 3;</code>
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      category_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string category = 3;</code>
     */
    public Builder clearCategory() {
      
      category_ = getDefaultInstance().getCategory();
      onChanged();
      return this;
    }
    /**
     * <code>string category = 3;</code>
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      category_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object star_ = "";
    /**
     * <code>string star = 4;</code>
     */
    public java.lang.String getStar() {
      java.lang.Object ref = star_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        star_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string star = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStarBytes() {
      java.lang.Object ref = star_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        star_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string star = 4;</code>
     */
    public Builder setStar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      star_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string star = 4;</code>
     */
    public Builder clearStar() {
      
      star_ = getDefaultInstance().getStar();
      onChanged();
      return this;
    }
    /**
     * <code>string star = 4;</code>
     */
    public Builder setStarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      star_ = value;
      onChanged();
      return this;
    }

    private java.util.List<kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        items_ = new java.util.ArrayList<kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage>(items_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage, kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.Builder, kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessageOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public java.util.List<kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public Builder setItems(
        int index, kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public Builder setItems(
        int index, kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public Builder addItems(kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public Builder addItems(
        int index, kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public Builder addItems(
        kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public Builder addItems(
        int index, kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessageOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public java.util.List<? extends kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessageOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage items = 5;</code>
     */
    public java.util.List<kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage, kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.Builder, kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessageOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage, kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage.Builder, kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessageOrBuilder>(
                items_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private java.lang.Object createAt_ = "";
    /**
     * <code>string create_at = 6;</code>
     */
    public java.lang.String getCreateAt() {
      java.lang.Object ref = createAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string create_at = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCreateAtBytes() {
      java.lang.Object ref = createAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string create_at = 6;</code>
     */
    public Builder setCreateAt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string create_at = 6;</code>
     */
    public Builder clearCreateAt() {
      
      createAt_ = getDefaultInstance().getCreateAt();
      onChanged();
      return this;
    }
    /**
     * <code>string create_at = 6;</code>
     */
    public Builder setCreateAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createAt_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updateAt_ = "";
    /**
     * <code>string update_at = 7;</code>
     */
    public java.lang.String getUpdateAt() {
      java.lang.Object ref = updateAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updateAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string update_at = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateAtBytes() {
      java.lang.Object ref = updateAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string update_at = 7;</code>
     */
    public Builder setUpdateAt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updateAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string update_at = 7;</code>
     */
    public Builder clearUpdateAt() {
      
      updateAt_ = getDefaultInstance().getUpdateAt();
      onChanged();
      return this;
    }
    /**
     * <code>string update_at = 7;</code>
     */
    public Builder setUpdateAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updateAt_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object timestamp_ = "";
    /**
     * <code>string timestamp = 8;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timestamp = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timestamp = 8;</code>
     */
    public Builder setTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 8;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = getDefaultInstance().getTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 8;</code>
     */
    public Builder setTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timestamp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object traceNo_ = "";
    /**
     * <code>string traceNo = 9;</code>
     */
    public java.lang.String getTraceNo() {
      java.lang.Object ref = traceNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string traceNo = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTraceNoBytes() {
      java.lang.Object ref = traceNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string traceNo = 9;</code>
     */
    public Builder setTraceNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      traceNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string traceNo = 9;</code>
     */
    public Builder clearTraceNo() {
      
      traceNo_ = getDefaultInstance().getTraceNo();
      onChanged();
      return this;
    }
    /**
     * <code>string traceNo = 9;</code>
     */
    public Builder setTraceNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      traceNo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage)
  }

  // @@protoc_insertion_point(class_scope:kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage)
  private static final kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage();
  }

  public static kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RhbOutputDataMessage>
      PARSER = new com.google.protobuf.AbstractParser<RhbOutputDataMessage>() {
    @java.lang.Override
    public RhbOutputDataMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RhbOutputDataMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RhbOutputDataMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RhbOutputDataMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

