// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RhbOutputDataItemMessage.proto

package kh.dev.scott.movie.core.proto.data.item;

public interface RhbOutputDataItemMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kh.dev.scott.movie.core.proto.data.item.RhbOutputDataItemMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string title = 2;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string category = 3;</code>
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 3;</code>
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>string star = 4;</code>
   */
  java.lang.String getStar();
  /**
   * <code>string star = 4;</code>
   */
  com.google.protobuf.ByteString
      getStarBytes();
}
