// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RhbOutputDataItemMessage.proto

package kh.dev.scott.movie.core.proto.data.item;

public final class RhbOutputDataItemMessageOuterClass {
  private RhbOutputDataItemMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kh_dev_scott_movie_core_proto_data_item_RhbOutputDataItemMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kh_dev_scott_movie_core_proto_data_item_RhbOutputDataItemMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036RhbOutputDataItemMessage.proto\022\'kh.dev" +
      ".scott.movie.core.proto.data.item\"U\n\030Rhb" +
      "OutputDataItemMessage\022\n\n\002id\030\001 \001(\003\022\r\n\005tit" +
      "le\030\002 \001(\t\022\020\n\010category\030\003 \001(\t\022\014\n\004star\030\004 \001(\t" +
      "B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kh_dev_scott_movie_core_proto_data_item_RhbOutputDataItemMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kh_dev_scott_movie_core_proto_data_item_RhbOutputDataItemMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kh_dev_scott_movie_core_proto_data_item_RhbOutputDataItemMessage_descriptor,
        new java.lang.String[] { "Id", "Title", "Category", "Star", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
