// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RhbOutputMessage.proto

package kh.dev.scott.movie.core.proto;

public interface RhbOutputMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kh.dev.scott.movie.core.proto.RhbOutputMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage data = 4;</code>
   */
  boolean hasData();
  /**
   * <code>.kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage data = 4;</code>
   */
  kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage getData();
  /**
   * <code>.kh.dev.scott.movie.core.proto.data.RhbOutputDataMessage data = 4;</code>
   */
  kh.dev.scott.movie.core.proto.data.RhbOutputDataMessageOrBuilder getDataOrBuilder();
}
