// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RhbOutputMessage.proto

package kh.dev.scott.movie.core.proto;

public final class RhbOutputMessageOuterClass {
  private RhbOutputMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kh_dev_scott_movie_core_proto_RhbOutputMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kh_dev_scott_movie_core_proto_RhbOutputMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026RhbOutputMessage.proto\022\035kh.dev.scott.m" +
      "ovie.core.proto\032\032RhbOutputDataMessage.pr" +
      "oto\"\211\001\n\020RhbOutputMessage\022\016\n\006status\030\001 \001(\t" +
      "\022\014\n\004code\030\002 \001(\t\022\017\n\007message\030\003 \001(\t\022F\n\004data\030" +
      "\004 \001(\01328.kh.dev.scott.movie.core.proto.da" +
      "ta.RhbOutputDataMessageB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          kh.dev.scott.movie.core.proto.data.RhbOutputDataMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_kh_dev_scott_movie_core_proto_RhbOutputMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kh_dev_scott_movie_core_proto_RhbOutputMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kh_dev_scott_movie_core_proto_RhbOutputMessage_descriptor,
        new java.lang.String[] { "Status", "Code", "Message", "Data", });
    kh.dev.scott.movie.core.proto.data.RhbOutputDataMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
